
Стартуем функцию test_func завершилась.
func_with_error тип ошибки <class 'ValueError'> с аргументами (), {}
Стартуем функцию test_func завершилась.
func_with_error тип ошибки <class 'ValueError'> с аргументами (), {}
